language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - platform-tools
    - tools

  licenses:
    - 'android-sdk-license.*'
script: ./gradlew build connectedCheck