language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - build-tools-27.0.3
    - build-tools-26.0.2
    - android-27
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - platform-tools
    - tools

  licenses:
    - 'android-sdk-license.*'
script: ./gradlew assembleRelease