language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-26.0.1
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - platform-tools

script:
  - ./gradlew build